name: Publish mod to Modrinth

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew clean build

      - name: Select JAR file
        id: findjar
        run: |
          fname=$(find build/libs -maxdepth 1 -type f -name "*.jar" \
            ! -name "*-sources.jar" ! -name "*-dev.jar" | head -n1)
          echo "jarname=$(basename \"$fname\")" >> $GITHUB_OUTPUT

      - name: Upload to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/${{ steps.findjar.outputs.jarname }}
          asset_name: ${{ steps.findjar.outputs.jarname }}
          asset_content_type: application/java-archive

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: gauDcTo0
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |
            fabric
          game-versions: |
            1.21.6
          files: build/libs/${{ steps.findjar.outputs.jarname }}
